### PR TITLE
Fix: Ensure --version flag works correctly for cargo stylus

### LINKED ISSUE #54: `--version` Option Returns Help Message Instead of Version
Executing `cargo stylus --version` returns a help message instead of the installed version of the tool. This flag only works for individual members, such as `cargo stylus cache --version`.

### PR DESCRIPTION
**Pull request by joewnga**
Fixes #54. The changes ensure that running `cargo stylus—-version` outputs the expected version information instead of returning the help message.

Also, resolved a minor issue with the duplication of the command `check` alias `c`.

## Checklist

- [x] I have documented these changes where necessary.
- [x] I have read the [DCO][DCO] and ensured that these changes comply.
- [x] I assign this work under its [open source licensing][terms].

[DCO]: https://github.com/OffchainLabs/cargo-stylus/licenses/DCO.txt
[terms]: https://github.com/OffchainLabs/cargo-stylus/licenses/COPYRIGHT.md

### CODE REVIEW

**Comment by joewnga** [comment]
@rauljordan kindly review. Thanks!

File: main/src/main.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@ enum Subcommands {
     /// Export a Solidity ABI.
     ExportAbi,
     /// Cache a contract.
-    #[command(alias = "c")]
+    #[command(alias = "a")]
```
Comment (rauljordan) [inline main/src/main.rs:37]:
```suggestion
```

File: main/src/main.rs [hunk 2]
```diff
@@ -78,6 +78,7 @@ const COMMANDS: &[Binary] = &[
             "reproducible",
             "n",
             "x",
+            "a",
```
Comment (rauljordan) [inline main/src/main.rs:81]:
```suggestion
```

**Review by rauljordan — APPROVED** [review]
